"use client";
import { useEffect, useRef, useState } from "react";
import { Calculator, CheckCircle2, CircleHelp, Download, FileText, FolderClock, Layers3, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton } from "@/components/ui/sidebar";
import { Toaster, toast } from "sonner";
import { sample, validate, type Config, type RecordItem, type Trial, type Issue } from "@/lib/domain";
type HistoryItem = { id:string; activityName:string; period:string; source:string; kind:string; result:Trial; createdAt:string };
const yuan=(v:string|number)=>{const text=String(v);const negative=text.startsWith("-");const [whole,fraction=""]=text.replace(/^-/,"").split(".");return `${negative?"-":""}${BigInt(whole).toLocaleString("zh-CN")}.${fraction.padEnd(2,"0")}`;};
const states:Record<string,string>={draft:"草稿",validated:"校验通过",submitted:"待审批",approved:"已批准"};
function Check({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){return <Checkbox aria-label={label} checked={checked} onCheckedChange={v=>onChange(v===true)}/>;}
function DataTable({heads,children}:{heads:string[];children:React.ReactNode}){return <Table><TableHeader><TableRow>{heads.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table>;}
export default function Workbench(){
 const [config,setConfig]=useState<Config>(sample),[saved,setSaved]=useState<RecordItem|null>(null),[activities,setActivities]=useState<RecordItem[]>([]);
 const [history,setHistory]=useState<HistoryItem[]>([]),[trial,setTrial]=useState<Trial|null>(null),[issues,setIssues]=useState<Issue[]|null>(null);
 const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[tab,setTab]=useState("config"),[view,setView]=useState("workbench"),[dialog,setDialog]=useState(false),[newName,setNewName]=useState("");
 const [connection,setConnection]=useState(""),[search,setSearch]=useState(""),[canReview,setCanReview]=useState(false),[detail,setDetail]=useState<HistoryItem|null>(null);
 const importRef=useRef<HTMLInputElement>(null),policyRef=useRef<HTMLInputElement>(null),historyRef=useRef<HTMLInputElement>(null),current=useRef(config);current.current=config;
 async function api(body?:unknown){const r=await fetch("/api/workbench",body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:undefined);const d=await r.json() as {error?:string;activities:RecordItem[];history:HistoryItem[];canReview:boolean;record:RecordItem;package:unknown};if(!r.ok)throw new Error(d.error||"操作失败");return d;}
 async function reload(){try{const d=await api();setActivities(d.activities);setHistory(d.history);setCanReview(d.canReview);setConnection("");}catch(e){setConnection((e as Error).message);}}
 useEffect(()=>{void reload();},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!context)return;const life=new AbortController();Promise.resolve(context.registerTool({name:"inspect_rebate_configuration",description:"读取当前活动摘要与本地校验问题，不保存或审批。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("不接受参数");return {name:current.current.name,issues:validate(current.current),members:current.current.members.length};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 function edit(c:Config){setConfig({...c,confirmed:false});setDirty(true);setTrial(null);setIssues(null);}
 function open(a:RecordItem){if(dirty&&!window.confirm("放弃未保存的修改并打开活动？"))return;setSaved(a);setConfig(a.config);setTrial(a.trial);setDirty(false);setIssues(null);setView("workbench");}
 async function act(action:string){setBusy(true);try{if(action==="save"||action==="trial"){if(action==="trial"){const es=validate(config);setIssues(es);if(es.length){setTab("config");toast.error(`有${es.length}项需要确认`);return;}}const d=await api({action,id:saved?.id,revision:saved?.revision,config});setSaved(d.record);setConfig(d.record.config);setTrial(d.record.trial);setDirty(false);if(action==="trial")setTab("trial");}else{if(!saved||dirty)throw new Error("请先保存并重新试算");const d=await api({action,id:saved.id,revision:saved.revision});if(d.record)setSaved(d.record);}toast.success(({save:"草稿已保存",trial:"试算完成",submit:"已提交审批",approve:"当前版本已批准",archive:"模拟试算已留档",reject:"已退回草稿"} as Record<string,string>)[action]);await reload();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function fresh(demo=false){if(dirty&&!window.confirm("放弃未保存的修改？"))return;const c=sample();if(!demo){c.name=newName.trim()||"未命名返利活动";c.policy="";c.metricNote="";c.members=[];c.products=[];c.transactions=[];}setConfig(c);setSaved(null);setTrial(null);setDirty(false);setIssues(null);setDialog(false);setView("workbench");setTab("config");}
 async function download(){if(!saved||dirty){toast.error("请先保存当前版本");return;}try{const d=await api({action:"export",id:saved.id,revision:saved.revision});const url=URL.createObjectURL(new Blob([JSON.stringify(d.package,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`rebate_${saved.id}_v${saved.version}.json`;a.click();URL.revokeObjectURL(url);toast.success("已导出；未导入SAP");}catch(e){toast.error((e as Error).message);}}
 type RowKey="members"|"products"|"tiers"|"transactions";
 function row(key:RowKey,i:number,field:string,value:unknown){edit({...config,[key]:config[key].map((r,n)=>n===i?{...r,[field]:value}:r)});}
 const inp=(key:RowKey,i:number,field:string,value:string,props:object={})=><input aria-label={`${key}第${i+1}行${field}`} className="cell-input" value={value} onChange={e=>row(key,i,field,e.target.value)} {...props}/>;
 const del=(key:RowKey,i:number)=><button className="icon-button" aria-label={`删除${key}第${i+1}行`} onClick={()=>edit({...config,[key]:config[key].filter((_,n)=>n!==i)})}><Trash2 size={15}/></button>;
 const state=dirty?"未保存":saved?states[saved.status]:"示例草稿";
 return <div className="app-shell"><Toaster richColors position="top-center"/><header className="topbar"><div className="brand"><span className="brand-mark"><Layers3 size={23}/></span><strong>返利配置工作台</strong><span className="edition">试点版</span></div><div className="identity"><ShieldCheck size={16}/>私人工作空间</div></header><SidebarProvider className="workspace"><Sidebar collapsible="none" className="sidebar"><SidebarHeader><div className="sidebar-heading">工作空间</div></SidebarHeader><SidebarContent><SidebarMenu>{[["workbench","活动配置",Layers3],["history","历史记录",FolderClock],["interface","接口与规则",FileText]].map(([key,label,Icon])=>{const I=Icon as typeof Layers3;return <SidebarMenuItem key={key as string}><SidebarMenuButton className="nav-item" isActive={view===key} onClick={()=>setView(key as string)}><I size={18}/>{label as string}</SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu><div className="sidebar-heading space">最近活动 <button aria-label="新建活动" onClick={()=>setDialog(true)}><Plus size={16}/></button></div><div className="activity-list">{activities.length?activities.slice(0,12).map(a=><button key={a.id} className={saved?.id===a.id?"activity selected":"activity"} onClick={()=>open(a)}><span>{a.config.name}</span><small>V{a.version} · {states[a.status]}</small></button>):<p className="quiet">保存第一份活动后，将在此显示。</p>}</div></SidebarContent><SidebarFooter className="sidebar-bottom"><div className="mini-label">当前业务范围</div><p>期末统一发放<br/>退货同步扣减两类金额<br/>历史结果独立留存</p><span className="tag">SAP 接口预留</span></SidebarFooter></Sidebar>
 <main><fieldset disabled={busy} className="request-lock"><div className="mobile-nav"><Select value={view} onValueChange={setView}><SelectTrigger aria-label="工作台导航"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="workbench">活动配置</SelectItem><SelectItem value="history">历史记录</SelectItem><SelectItem value="interface">接口与规则</SelectItem></SelectContent></Select>{activities.length>0&&<Select value={saved?.id||""} onValueChange={id=>{const a=activities.find(x=>x.id===id);if(a)open(a);}}><SelectTrigger aria-label="打开已保存活动"><SelectValue placeholder="打开已保存活动"/></SelectTrigger><SelectContent>{activities.map(a=><SelectItem key={a.id} value={a.id}>{a.config.name} · V{a.version}</SelectItem>)}</SelectContent></Select>}</div><div className="breadcrumb">返利管理 <span>/</span> {view==="history"?"历史记录":view==="interface"?"接口与规则":"活动配置"}</div>{connection&&<div className="notice error" role="alert">数据服务暂不可用：{connection}<button onClick={()=>reload()}>重试</button></div>}
 {view==="workbench"&&<><div className="page-heading"><div><div className="eyebrow">POLICY WORKSPACE</div><h1>{config.name}</h1><div className="meta"><span className="tag">{state}</span><span>V{saved?.version||1}</span><span>人民币 CNY</span><span>期末统一处理</span></div></div><div className="actions"><button className="button" onClick={()=>setDialog(true)}><Plus size={16}/>新建活动</button><button className="button" disabled={busy} onClick={()=>act("save")}><Save size={16}/>保存草稿</button><button className="button primary" disabled={busy} onClick={()=>act("trial")}><Calculator size={16}/>{busy?"处理中…":"校验并试算"}</button></div></div><div className="workflow">{["政策与口径","规则配置","校验试算","审批与导出"].map((s,i)=><div key={s} className={i<2||i===2&&trial||i===3&&saved?.status==="approved"?"step done":"step"}><span>{i+1}</span>{s}</div>)}</div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="work-tabs" variant="line"><TabsTrigger value="config">规则配置</TabsTrigger><TabsTrigger value="transactions">试算明细 <span className="count">{config.transactions.length}</span></TabsTrigger><TabsTrigger value="trial">试算结果</TabsTrigger><TabsTrigger value="review">审批与导出</TabsTrigger></TabsList>
 <TabsContent value="config"><div className="config-grid"><div><section className="panel"><div className="panel-heading"><h2><span>01</span>活动与政策</h2><button className="text-button" onClick={()=>policyRef.current?.click()}>导入政策文本</button><input hidden ref={policyRef} type="file" accept=".txt,.md" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>300000){toast.error("政策文本最多300KB");return;}edit({...config,policy:await f.text()});e.target.value="";}}/></div><div className="form-grid"><label className="wide">活动名称<input value={config.name} onChange={e=>edit({...config,name:e.target.value})}/></label><label>开始日期<input type="date" value={config.periodStart} onChange={e=>edit({...config,periodStart:e.target.value})}/></label><label>结束日期（不含当日）<input type="date" value={config.periodEnd} onChange={e=>edit({...config,periodEnd:e.target.value})}/></label><label className="wide">政策原文 / 规则依据<textarea rows={5} value={config.policy} onChange={e=>edit({...config,policy:e.target.value})} placeholder="粘贴政策原文并配置对应规则"/></label><label className="wide">金额与日期口径<textarea rows={3} value={config.metricNote} onChange={e=>edit({...config,metricNote:e.target.value})} placeholder="填写取数、税、日期、退货归属及舍入依据"/></label></div><p className="help">支持粘贴原文或导入TXT / Markdown，规则须人工确认；尚未接入大模型和OCR。</p></section>
 <section className="panel"><div className="panel-heading"><h2><span>02</span>核算组与成员</h2><button className="text-button" onClick={()=>edit({...config,members:[...config.members,{code:"",name:"",group:"G",threshold:true,rebate:true}]})}><Plus size={15}/>添加成员</button></div><DataTable heads={["成员编码","成员名称","核算组","计入台阶","返利资格",""]}>{config.members.map((m,i)=><TableRow key={i}><TableCell>{inp("members",i,"code",m.code)}</TableCell><TableCell>{inp("members",i,"name",m.name)}</TableCell><TableCell>{inp("members",i,"group",m.group)}</TableCell><TableCell><Check label={`成员${m.code}台阶资格`} checked={m.threshold} onChange={v=>row("members",i,"threshold",v)}/></TableCell><TableCell><Check label={`成员${m.code}返利资格`} checked={m.rebate} onChange={v=>row("members",i,"rebate",v)}/></TableCell><TableCell>{del("members",i)}</TableCell></TableRow>)}</DataTable><p className="help">同组共享达成系数，各子抬头分别计算奖励。首期不处理期中关系变化。</p></section>
 <section className="panel"><div className="panel-heading"><h2><span>03</span>产品与基础比例</h2><button className="text-button" onClick={()=>edit({...config,products:[...config.products,{code:"",name:"",threshold:true,rebate:true,rate:"0.02"}]})}><Plus size={15}/>添加产品</button></div><DataTable heads={["产品编码","产品名称","计入台阶","计入返利","基础比例",""]}>{config.products.map((p,i)=><TableRow key={i}><TableCell>{inp("products",i,"code",p.code)}</TableCell><TableCell>{inp("products",i,"name",p.name)}</TableCell><TableCell><Check label={`产品${p.code}台阶资格`} checked={p.threshold} onChange={v=>row("products",i,"threshold",v)}/></TableCell><TableCell><Check label={`产品${p.code}返利资格`} checked={p.rebate} onChange={v=>row("products",i,"rebate",v)}/></TableCell><TableCell>{inp("products",i,"rate",p.rate)}</TableCell><TableCell>{del("products",i)}</TableCell></TableRow>)}</DataTable><p className="help">比例按小数填写：0.02 = 2%。退货同步扣减两类金额。</p></section>
 <section className="panel"><div className="panel-heading"><h2><span>04</span>阶梯与系数</h2><Select value={config.template} onValueChange={v=>edit({...config,template:v as Config["template"]})}><SelectTrigger aria-label="规则模板" className="template-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="group">基础比例 × 核算组系数</SelectItem><SelectItem value="fixed">固定比例</SelectItem></SelectContent></Select></div>{config.template==="group"?<><DataTable heads={["台阶下限（含）","台阶上限（不含）","达成系数",""]}>{config.tiers.map((t,i)=><TableRow key={i}><TableCell>{inp("tiers",i,"min",t.min)}</TableCell><TableCell>{inp("tiers",i,"max",t.max,{placeholder:"无上限"})}</TableCell><TableCell>{inp("tiers",i,"factor",t.factor)}</TableCell><TableCell>{del("tiers",i)}</TableCell></TableRow>)}</DataTable><button className="text-button add-tier" onClick={()=>edit({...config,tiers:[...config.tiers,{min:"",max:"",factor:"1"}]})}><Plus size={15}/>添加阶梯</button></>:<p className="help">固定比例模式不使用阶梯，系数为1，按各产品基础比例计算。</p>}</section></div>
 <aside className="context-column"><section className="rule-note"><div className="mini-label">计算关系</div><h3>合并达标<br/>分别返利</h3><div className="formula"><span>核算组台阶金额</span><strong>匹配共享系数</strong><span>子抬头基数 × 基础比例</span><strong>× 共享系数</strong><hr/><span>子抬头奖励金额</span></div></section><section className="panel compact"><h3>本期规则</h3><ul className="rule-list">{["退货同步扣减两类金额","期末统一发放","历史结果独立留存","不做退货扣款或追回","不含封顶与互斥"].map(t=><li key={t}><CheckCircle2 size={15}/>{t}</li>)}</ul></section><section className="panel compact"><h3><CircleHelp size={16}/>试算约定</h3><p className="help">负净台阶系数为0，无可发奖励时为0；子抬头汇总后四舍五入至分。正式使用前须确认。</p></section></aside></div><div className="confirmation"><Check label="确认配置与口径" checked={config.confirmed} onChange={v=>{setConfig({...config,confirmed:v});setDirty(true);setTrial(null);}}/><span>我已核对政策依据、成员、产品、金额口径及试算约定，确认当前配置。</span></div>{issues&&<div className={issues.length?"notice error":"notice success"} role="status">{issues.length?<><strong>{issues.length}项问题需要处理</strong><ul>{issues.map((e,i)=><li key={i}>{e.field}：{e.message}</li>)}</ul></>:"规则校验通过"}</div>}</TabsContent>
 <TabsContent value="transactions"><section className="panel"><div className="panel-heading"><div><h2>试算交易明细</h2><p className="help">金额单位：元。负数表示退货。</p></div><div className="actions"><button className="button" onClick={()=>{if(config.transactions.some(t=>t.id==="RETURN-DEMO")){toast.info("退货案例已存在");return;}edit({...config,transactions:[...config.transactions,{id:"RETURN-DEMO",member:config.members[0]?.code||"A",product:config.products[0]?.code||"X",amount:"-100000",date:config.periodStart}]});toast.success("已添加10万元退货，请重新确认配置");}}>添加退货案例</button><button className="button" onClick={()=>importRef.current?.click()}>导入JSON</button><input hidden ref={importRef} type="file" accept=".json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000)throw new Error("最多2MB");const rows=JSON.parse(await f.text());if(!Array.isArray(rows)||rows.length>10000||!rows.every(r=>r&&["id","member","product","amount","date"].every(k=>typeof r[k]==="string")))throw new Error("需包含id、member、product、amount、date字符串字段的数组");edit({...config,transactions:rows});toast.success("导入成功，待校验");}catch(err){toast.error((err as Error).message);}e.target.value="";}}/><button className="button primary" onClick={()=>edit({...config,transactions:[...config.transactions,{id:crypto.randomUUID().slice(0,8),member:"",product:"",amount:"0",date:config.periodStart}]})}><Plus size={16}/>新增明细</button></div></div><DataTable heads={["唯一编号","成员编码","产品编码","金额（元）","业务日期",""]}>{config.transactions.map((t,i)=><TableRow key={i}><TableCell>{inp("transactions",i,"id",t.id)}</TableCell><TableCell>{inp("transactions",i,"member",t.member)}</TableCell><TableCell>{inp("transactions",i,"product",t.product)}</TableCell><TableCell>{inp("transactions",i,"amount",t.amount)}</TableCell><TableCell>{inp("transactions",i,"date",t.date,{type:"date"})}</TableCell><TableCell>{del("transactions",i)}</TableCell></TableRow>)}</DataTable></section></TabsContent>
 <TabsContent value="trial">{trial?<><TrialView trial={trial}/><div className="actions bottom"><button className="button" disabled={busy||dirty} onClick={()=>act("archive")}><FolderClock size={16}/>保存试算快照</button><button className="button primary" disabled={busy||dirty||saved?.status!=="validated"} onClick={()=>act("submit")}>提交审批</button></div></>:<Empty title="当前版本尚未试算" text="确认配置与口径后点击“校验并试算”。修改配置将使旧试算失效。"/>}</TabsContent>
 <TabsContent value="review"><section className="panel review-panel"><ShieldCheck className="large-icon"/><h2>审批绑定当前配置版本</h2><p>状态：{state} · V{saved?.version||1}</p><p className="help">提交人与审批人必须分离，审批权限在服务端配置。私人试点不会模拟他人批准。</p><div className="actions"><button className="button primary" disabled={busy||dirty||saved?.status!=="validated"} onClick={()=>act("submit")}>提交审批</button><button className="button" disabled={busy||dirty||saved?.status!=="submitted"||!canReview} onClick={()=>act("approve")}>批准</button><button className="button" disabled={busy||dirty||saved?.status!=="submitted"||!canReview} onClick={()=>act("reject")}>退回</button><button className="button" onClick={()=>download()}><Download size={16}/>导出配置包</button></div><p className="help">待审批包标记为草稿。导出不代表SAP发布或奖励发放。</p>{saved?.digest&&<div className="digest">配置摘要 · {saved.digest}</div>}</section></TabsContent></Tabs></>}
 {view==="history"&&<><div className="page-heading"><div><div className="eyebrow">RECORDS & TRACEABILITY</div><h1>历史记录</h1><p className="muted">冻结结果与规则版本，保留计算依据。</p></div></div><section className="panel"><div className="panel-heading"><h2>留存记录 <span className="count">{history.length}</span></h2><button className="button" onClick={()=>historyRef.current?.click()}>导入已完成核算</button><input hidden ref={historyRef} type="file" accept=".json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>2500000)throw new Error("文件最多2.5MB");const response=await fetch("/api/history",{method:"POST",headers:{"Content-Type":"application/json"},body:await file.text()});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"导入失败");toast.success("历史核算已留存，发放状态未确认");await reload();}catch(err){toast.error((err as Error).message);}e.target.value="";}}/><input aria-label="搜索历史记录" placeholder="搜索活动名称" value={search} onChange={e=>setSearch(e.target.value)}/></div>{history.length?<DataTable heads={["活动名称","期间","类型","奖励合计","留存时间","操作"]}>{history.filter(h=>h.activityName.includes(search)).map(h=><TableRow key={h.id}><TableCell>{h.activityName}</TableCell><TableCell>{h.period}</TableCell><TableCell><span className="tag">{h.kind==="simulation"?"模拟试算":"历史核算"}</span></TableCell><TableCell>¥{yuan(h.result.total)}</TableCell><TableCell>{new Date(h.createdAt).toLocaleString("zh-CN")}</TableCell><TableCell><button className="text-button" onClick={()=>setDetail(h)}>查看快照</button></TableCell></TableRow>)}</DataTable>:<Empty title="暂无历史记录" text="试算后可保存快照。模拟记录与正式核算分别标识。"/>}</section><p className="help">可导入JSON格式的已完成核算结果，需附活动、期间、完成时间、外部批次和来源。相同批次不能覆盖已有结果。<a href="/examples/history.json" download>下载导入示例</a></p></>}
 {view==="interface"&&<><div className="page-heading"><div><div className="eyebrow">INTEGRATION CONTRACT</div><h1>接口与规则</h1><p className="muted">标准配置可导出，SAP保留接口，不进行实际对接。</p></div><span className="tag">未连接 SAP</span></div><section className="panel"><h2>接口边界</h2><DataTable heads={["能力","本期状态","交付内容"]}>{[["配置输出","已实现","规则版本、口径与配置摘要"],["试算","本地模拟","台阶、系数、子抬头基数和奖励"],["SAP导入 / 回读 / 激活","接口预留","不发送真实请求"],["历史核算结果","手动导入","保留外部核算批次、结果与来源"],["奖励发放","沿用既有系统","不执行支付、扣款或追回"]].map(r=><TableRow key={r[0]}>{r.map(c=><TableCell key={c}>{c}</TableCell>)}</TableRow>)}</DataTable></section><section className="panel"><h2>已确认的退货规则</h2><p>退货同时减少台阶金额和返利基数，不产生退货扣款或奖励追回。</p><div className="example"><span>A退货10万元</span><strong>集团台阶190万元 · 系数1.0</strong><p>A奖励10,000元 · B奖励12,000元</p></div></section><section className="panel"><h2>当前开发边界</h2><p className="help">PDF、DOCX、XLSX自动解析、OCR、模型提取和企业主数据同步尚未接入。当前版本验证人工配置、校验、试算与留档流程。</p></section></>}
 </fieldset><footer>返利政策配置工作台 <span>政策有据 · 规则可查 · 结果可追溯</span></footer></main></SidebarProvider>
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogHeader><DialogTitle>新建返利活动</DialogTitle><DialogDescription>填写政策、成员及产品后，校验并试算。</DialogDescription></DialogHeader><label>活动名称<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="2026年第四季度新品返利"/></label><button className="button primary" onClick={()=>fresh()}>创建空白草稿</button><button className="button" onClick={()=>fresh(true)}>载入标准示例</button></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={o=>{if(!o)setDetail(null);}}><DialogContent className="history-dialog"><DialogHeader><DialogTitle>{detail?.activityName}</DialogTitle><DialogDescription>不可修改的快照 · {detail?.source}</DialogDescription></DialogHeader>{detail&&<TrialView trial={detail.result}/>}</DialogContent></Dialog></div>;
}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Calculator size={32}/><h3>{title}</h3><p>{text}</p></div>;}
function TrialView({trial}:{trial:Trial}){return <><div className="notice info"><CircleHelp size={18}/>{trial.mode==="historical"?"外部历史核算 · 发放状态未确认":"模拟试算 · 未执行SAP核算或发放"}</div><div className="result-stats"><div><span>奖励合计</span><strong>¥{yuan(trial.total)}</strong></div><div><span>核算组</span><strong>{trial.groups.length}<small>组</small></strong></div><div><span>子抬头</span><strong>{trial.children.length}<small>个</small></strong></div></div><section className="panel"><h2>核算组达成情况</h2><DataTable heads={["核算组","台阶净额","共享系数"]}>{trial.groups.map(g=><TableRow key={g.code}><TableCell>{g.code}</TableCell><TableCell>¥{yuan(g.threshold)}</TableCell><TableCell><strong>{g.factor}</strong></TableCell></TableRow>)}</DataTable></section><section className="panel"><h2>子抬头返利结果</h2><DataTable heads={["子抬头","核算组","台阶净额","返利净基数","退货金额","系数","奖励金额"]}>{trial.children.map(c=><TableRow key={c.code}><TableCell>{c.name} <small>{c.code}</small></TableCell><TableCell>{c.group}</TableCell><TableCell>{yuan(c.threshold)}</TableCell><TableCell>{yuan(c.base)}</TableCell><TableCell className={c.returns.startsWith("-")?"negative":""}>{yuan(c.returns)}</TableCell><TableCell>{c.factor}</TableCell><TableCell><strong className="amount">¥{yuan(c.reward)}</strong></TableCell></TableRow>)}</DataTable></section><div className="help">{trial.notices.map(n=><p key={n}>{n}</p>)}</div></>;}
